name: CD

on: [push]

jobs:
  publish:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Git config NAME
      run: git config user.name "$GITHUB_ACTOR"
      
    - name: Git config EMAIL
      run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
    - name: NPM version patch
      run: npm version patch
     
    - name: Restore packages
      run: npm install
      
    - name: Build library
      run: npm run build

    - name: NPM config
      run: npm config set //npm.pkg.github.com/:_authToken=$TOKEN
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: NPM publish
      run: npm publish
