name: CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      
    - name: Patch version
      run: npm version patch
      
    - name: Restore packages
      run: npm install
      
    - name: Build library
      run: npm run build
    
    
