name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      
    - name: Restore packages
      run: npm i
      
    - name: Build library
      run: npm run build
